/**
 * Centralised icon exports. Import once per file from here so we
 * do not repeat deep paths or inline SVGs anywhere else.
 */
export {
  MagnifyingGlassIcon,
  ShoppingCartIcon,
  UserIcon,
  Bars3Icon,
  XMarkIcon,
  ChevronDownIcon,
  ChevronRightIcon,
  ChevronLeftIcon,
  ChevronUpIcon,
  PhoneIcon,
  EnvelopeIcon,
  MapPinIcon,
  HeartIcon,
  EyeIcon,
  ScaleIcon,
  PlusIcon,
  MinusIcon,
  TrashIcon,
  CheckIcon,
  CheckCircleIcon,
  ExclamationCircleIcon,
  ExclamationTriangleIcon,
  InformationCircleIcon,
  XCircleIcon,
  ArrowRightIcon,
  ArrowLeftIcon,
  ArrowLongRightIcon,
  ArrowPathIcon,
  TruckIcon,
  ShieldCheckIcon,
  BuildingStorefrontIcon,
  BuildingOffice2Icon,
  AcademicCapIcon,
  BookOpenIcon,
  GlobeAltIcon,
  LanguageIcon,
  SparklesIcon,
  FireIcon,
  TagIcon,
  GiftIcon,
  ClockIcon,
  StarIcon,
  LockClosedIcon,
  CreditCardIcon,
  BanknotesIcon,
  DocumentTextIcon,
  Squares2X2Icon,
  ListBulletIcon,
  AdjustmentsHorizontalIcon,
  FunnelIcon,
  Cog6ToothIcon,
  BellIcon,
  EyeSlashIcon,
  ArrowRightOnRectangleIcon,
  ArrowLeftOnRectangleIcon,
} from "@heroicons/react/24/outline";

export {
  HeartIcon as HeartIconSolid,
  StarIcon as StarIconSolid,
  CheckCircleIcon as CheckCircleIconSolid,
  ExclamationCircleIcon as ExclamationCircleIconSolid,
  XCircleIcon as XCircleIconSolid,
  InformationCircleIcon as InformationCircleIconSolid,
} from "@heroicons/react/24/solid";
